# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := STM32_UbidotsMBED


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += HTS221/HTS221Sensor.o
OBJECTS += HTS221/HTS221_driver.o
OBJECTS += LIS3MDL/lis3mdl_class.o
OBJECTS += LPS22HB/LPS22HBSensor.o
OBJECTS += LPS22HB/LPS22HB_driver.o
OBJECTS += LSM303AGR/LSM303AGRAccSensor.o
OBJECTS += LSM303AGR/LSM303AGRMagSensor.o
OBJECTS += LSM303AGR/LSM303AGR_acc_driver.o
OBJECTS += LSM303AGR/LSM303AGR_mag_driver.o
OBJECTS += LSM6DSL/LSM6DSLSensor.o
OBJECTS += LSM6DSL/LSM6DSL_acc_gyro_driver.o
OBJECTS += VL53L0X/VL53L0X.o
OBJECTS += main.o
OBJECTS += mbed-os/drivers/AnalogIn.o
OBJECTS += mbed-os/drivers/BusIn.o
OBJECTS += mbed-os/drivers/BusInOut.o
OBJECTS += mbed-os/drivers/BusOut.o
OBJECTS += mbed-os/drivers/CAN.o
OBJECTS += mbed-os/drivers/Ethernet.o
OBJECTS += mbed-os/drivers/FlashIAP.o
OBJECTS += mbed-os/drivers/I2C.o
OBJECTS += mbed-os/drivers/I2CSlave.o
OBJECTS += mbed-os/drivers/InterruptIn.o
OBJECTS += mbed-os/drivers/InterruptManager.o
OBJECTS += mbed-os/drivers/RawSerial.o
OBJECTS += mbed-os/drivers/SPI.o
OBJECTS += mbed-os/drivers/SPISlave.o
OBJECTS += mbed-os/drivers/Serial.o
OBJECTS += mbed-os/drivers/SerialBase.o
OBJECTS += mbed-os/drivers/Ticker.o
OBJECTS += mbed-os/drivers/Timeout.o
OBJECTS += mbed-os/drivers/Timer.o
OBJECTS += mbed-os/drivers/TimerEvent.o
OBJECTS += mbed-os/drivers/UARTSerial.o
OBJECTS += mbed-os/events/EventQueue.o
OBJECTS += mbed-os/events/equeue/equeue.o
OBJECTS += mbed-os/events/equeue/equeue_mbed.o
OBJECTS += mbed-os/events/equeue/equeue_posix.o
OBJECTS += mbed-os/events/mbed_shared_queues.o
OBJECTS += mbed-os/features/filesystem/Dir.o
OBJECTS += mbed-os/features/filesystem/File.o
OBJECTS += mbed-os/features/filesystem/FileSystem.o
OBJECTS += mbed-os/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ExhaustibleBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/MBRBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ObservingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ProfilingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ReadOnlyBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ff.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ffunicode.o
OBJECTS += mbed-os/features/filesystem/fat/FATFileSystem.o
OBJECTS += mbed-os/features/filesystem/littlefs/LittleFileSystem.o
OBJECTS += mbed-os/features/filesystem/littlefs/littlefs/lfs.o
OBJECTS += mbed-os/features/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += mbed-os/features/frameworks/unity/source/unity.o
OBJECTS += mbed-os/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/unity_handler.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_case.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_harness.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_types.o
OBJECTS += mbed-os/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += mbed-os/features/mbedtls/src/aes.o
OBJECTS += mbed-os/features/mbedtls/src/aesni.o
OBJECTS += mbed-os/features/mbedtls/src/arc4.o
OBJECTS += mbed-os/features/mbedtls/src/asn1parse.o
OBJECTS += mbed-os/features/mbedtls/src/asn1write.o
OBJECTS += mbed-os/features/mbedtls/src/base64.o
OBJECTS += mbed-os/features/mbedtls/src/bignum.o
OBJECTS += mbed-os/features/mbedtls/src/blowfish.o
OBJECTS += mbed-os/features/mbedtls/src/camellia.o
OBJECTS += mbed-os/features/mbedtls/src/ccm.o
OBJECTS += mbed-os/features/mbedtls/src/certs.o
OBJECTS += mbed-os/features/mbedtls/src/cipher.o
OBJECTS += mbed-os/features/mbedtls/src/cipher_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/cmac.o
OBJECTS += mbed-os/features/mbedtls/src/ctr_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/debug.o
OBJECTS += mbed-os/features/mbedtls/src/des.o
OBJECTS += mbed-os/features/mbedtls/src/dhm.o
OBJECTS += mbed-os/features/mbedtls/src/ecdh.o
OBJECTS += mbed-os/features/mbedtls/src/ecdsa.o
OBJECTS += mbed-os/features/mbedtls/src/ecjpake.o
OBJECTS += mbed-os/features/mbedtls/src/ecp.o
OBJECTS += mbed-os/features/mbedtls/src/ecp_curves.o
OBJECTS += mbed-os/features/mbedtls/src/entropy.o
OBJECTS += mbed-os/features/mbedtls/src/entropy_poll.o
OBJECTS += mbed-os/features/mbedtls/src/error.o
OBJECTS += mbed-os/features/mbedtls/src/gcm.o
OBJECTS += mbed-os/features/mbedtls/src/havege.o
OBJECTS += mbed-os/features/mbedtls/src/hmac_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/md.o
OBJECTS += mbed-os/features/mbedtls/src/md2.o
OBJECTS += mbed-os/features/mbedtls/src/md4.o
OBJECTS += mbed-os/features/mbedtls/src/md5.o
OBJECTS += mbed-os/features/mbedtls/src/md_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += mbed-os/features/mbedtls/src/net_sockets.o
OBJECTS += mbed-os/features/mbedtls/src/oid.o
OBJECTS += mbed-os/features/mbedtls/src/padlock.o
OBJECTS += mbed-os/features/mbedtls/src/pem.o
OBJECTS += mbed-os/features/mbedtls/src/pk.o
OBJECTS += mbed-os/features/mbedtls/src/pk_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs11.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs12.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs5.o
OBJECTS += mbed-os/features/mbedtls/src/pkparse.o
OBJECTS += mbed-os/features/mbedtls/src/pkwrite.o
OBJECTS += mbed-os/features/mbedtls/src/platform.o
OBJECTS += mbed-os/features/mbedtls/src/ripemd160.o
OBJECTS += mbed-os/features/mbedtls/src/rsa.o
OBJECTS += mbed-os/features/mbedtls/src/sha1.o
OBJECTS += mbed-os/features/mbedtls/src/sha256.o
OBJECTS += mbed-os/features/mbedtls/src/sha512.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cache.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cli.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cookie.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_srv.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ticket.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_tls.o
OBJECTS += mbed-os/features/mbedtls/src/threading.o
OBJECTS += mbed-os/features/mbedtls/src/timing.o
OBJECTS += mbed-os/features/mbedtls/src/version.o
OBJECTS += mbed-os/features/mbedtls/src/version_features.o
OBJECTS += mbed-os/features/mbedtls/src/x509.o
OBJECTS += mbed-os/features/mbedtls/src/x509_create.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crl.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509_csr.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_csr.o
OBJECTS += mbed-os/features/mbedtls/src/xtea.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/aes_alt.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/md5_alt.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/sha1_alt.o
OBJECTS += mbed-os/features/mbedtls/targets/TARGET_STM/sha256_alt.o
OBJECTS += mbed-os/features/netsocket/NetworkInterface.o
OBJECTS += mbed-os/features/netsocket/NetworkStack.o
OBJECTS += mbed-os/features/netsocket/Socket.o
OBJECTS += mbed-os/features/netsocket/SocketAddress.o
OBJECTS += mbed-os/features/netsocket/TCPServer.o
OBJECTS += mbed-os/features/netsocket/TCPSocket.o
OBJECTS += mbed-os/features/netsocket/UDPSocket.o
OBJECTS += mbed-os/features/netsocket/WiFiAccessPoint.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.o
OBJECTS += mbed-os/features/netsocket/nsapi_dns.o
OBJECTS += mbed-os/hal/mbed_flash_api.o
OBJECTS += mbed-os/hal/mbed_gpio.o
OBJECTS += mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += mbed-os/hal/mbed_pinmap_common.o
OBJECTS += mbed-os/hal/mbed_sleep_manager.o
OBJECTS += mbed-os/hal/mbed_ticker_api.o
OBJECTS += mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += mbed-os/platform/ATCmdParser.o
OBJECTS += mbed-os/platform/CallChain.o
OBJECTS += mbed-os/platform/FileBase.o
OBJECTS += mbed-os/platform/FileHandle.o
OBJECTS += mbed-os/platform/FilePath.o
OBJECTS += mbed-os/platform/FileSystemHandle.o
OBJECTS += mbed-os/platform/LocalFileSystem.o
OBJECTS += mbed-os/platform/Stream.o
OBJECTS += mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += mbed-os/platform/mbed_application.o
OBJECTS += mbed-os/platform/mbed_assert.o
OBJECTS += mbed-os/platform/mbed_board.o
OBJECTS += mbed-os/platform/mbed_critical.o
OBJECTS += mbed-os/platform/mbed_error.o
OBJECTS += mbed-os/platform/mbed_interface.o
OBJECTS += mbed-os/platform/mbed_mem_trace.o
OBJECTS += mbed-os/platform/mbed_mktime.o
OBJECTS += mbed-os/platform/mbed_poll.o
OBJECTS += mbed-os/platform/mbed_retarget.o
OBJECTS += mbed-os/platform/mbed_rtc_time.o
OBJECTS += mbed-os/platform/mbed_sdk_boot.o
OBJECTS += mbed-os/platform/mbed_semihost_api.o
OBJECTS += mbed-os/platform/mbed_stats.o
OBJECTS += mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += mbed-os/rtos/ConditionVariable.o
OBJECTS += mbed-os/rtos/EventFlags.o
OBJECTS += mbed-os/rtos/Kernel.o
OBJECTS += mbed-os/rtos/Mutex.o
OBJECTS += mbed-os/rtos/RtosTimer.o
OBJECTS += mbed-os/rtos/Semaphore.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_boot.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += mbed-os/rtos/Thread.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/system_clock.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/startup_stm32l475xx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/analogin_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/analogout_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can_legacy.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_comp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cortex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dcmi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma2d.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dsi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_firewall.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ramfunc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gfxmmu.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gpio.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_irda.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_iwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lptim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nand.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nor.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ospi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_qspi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rng.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smbus.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sram.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_swpmi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tsc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart_ex.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_wwdg.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_adc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_comp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crs.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dac.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma2d.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_exti.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_fmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_gpio.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_i2c.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lptim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lpuart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_opamp.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_pwr.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rcc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rng.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rtc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_sdmmc.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_spi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_swpmi.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_tim.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usart.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usb.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_utils.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/system_stm32l4xx.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/flash_api.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/gpio_irq_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/pwmout_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/serial_device.o
OBJECTS += mbed-os/targets/TARGET_STM/TARGET_STM32L4/spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/analogin_api.o
OBJECTS += mbed-os/targets/TARGET_STM/analogout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/hal_tick_32b.o
OBJECTS += mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += mbed-os/targets/TARGET_STM/mbed_overrides.o
OBJECTS += mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += mbed-os/targets/TARGET_STM/serial_api.o
OBJECTS += mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_16b.o
OBJECTS += mbed-os/targets/TARGET_STM/us_ticker_32b.o
OBJECTS += wifi-ism43362/ISM43362/ATParser/ATParser.o
OBJECTS += wifi-ism43362/ISM43362/ATParser/BufferedSpi/Buffer/MyBuffer.o
OBJECTS += wifi-ism43362/ISM43362/ATParser/BufferedSpi/BufferedPrint.o
OBJECTS += wifi-ism43362/ISM43362/ATParser/BufferedSpi/BufferedSpi.o
OBJECTS += wifi-ism43362/ISM43362/ISM43362.o
OBJECTS += wifi-ism43362/ISM43362Interface.o
OBJECTS += wifi-x-nucleo-idw01m1/SPWFSA01/SPWFSA01.o
OBJECTS += wifi-x-nucleo-idw01m1/SPWFSA04/SPWFSA04.o
OBJECTS += wifi-x-nucleo-idw01m1/SPWFSAxx.o
OBJECTS += wifi-x-nucleo-idw01m1/SpwfSAInterface.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../HTS221
INCLUDE_PATHS += -I../HTS221/ST_INTERFACES
INCLUDE_PATHS += -I../HTS221/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../HTS221/ST_INTERFACES/Common
INCLUDE_PATHS += -I../HTS221/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../HTS221/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../HTS221/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../HTS221/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../HTS221/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../HTS221/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../LIS3MDL
INCLUDE_PATHS += -I../LIS3MDL/ST_INTERFACES
INCLUDE_PATHS += -I../LIS3MDL/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../LIS3MDL/ST_INTERFACES/Common
INCLUDE_PATHS += -I../LIS3MDL/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../LIS3MDL/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../LIS3MDL/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../LIS3MDL/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../LIS3MDL/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../LIS3MDL/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../LPS22HB
INCLUDE_PATHS += -I../LPS22HB/ST_INTERFACES
INCLUDE_PATHS += -I../LPS22HB/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../LPS22HB/ST_INTERFACES/Common
INCLUDE_PATHS += -I../LPS22HB/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../LPS22HB/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../LPS22HB/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../LPS22HB/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../LPS22HB/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../LPS22HB/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../LSM303AGR
INCLUDE_PATHS += -I../LSM303AGR/ST_INTERFACES
INCLUDE_PATHS += -I../LSM303AGR/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../LSM303AGR/ST_INTERFACES/Common
INCLUDE_PATHS += -I../LSM303AGR/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../LSM303AGR/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../LSM303AGR/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../LSM303AGR/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../LSM303AGR/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../LSM303AGR/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../LSM6DSL
INCLUDE_PATHS += -I../LSM6DSL/ST_INTERFACES
INCLUDE_PATHS += -I../LSM6DSL/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../LSM6DSL/ST_INTERFACES/Common
INCLUDE_PATHS += -I../LSM6DSL/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../LSM6DSL/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../LSM6DSL/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../LSM6DSL/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../LSM6DSL/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../LSM6DSL/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../VL53L0X
INCLUDE_PATHS += -I../VL53L0X/STMPE1600
INCLUDE_PATHS += -I../VL53L0X/ST_INTERFACES
INCLUDE_PATHS += -I../VL53L0X/ST_INTERFACES/Actuators
INCLUDE_PATHS += -I../VL53L0X/ST_INTERFACES/Common
INCLUDE_PATHS += -I../VL53L0X/ST_INTERFACES/Communications
INCLUDE_PATHS += -I../VL53L0X/ST_INTERFACES/Sensors
INCLUDE_PATHS += -I../VL53L0X/X_NUCLEO_COMMON
INCLUDE_PATHS += -I../VL53L0X/X_NUCLEO_COMMON/DbgMCU
INCLUDE_PATHS += -I../VL53L0X/X_NUCLEO_COMMON/DevI2C
INCLUDE_PATHS += -I../VL53L0X/X_NUCLEO_COMMON/DevSPI
INCLUDE_PATHS += -I../mbed-os/.
INCLUDE_PATHS += -I../mbed-os/cmsis
INCLUDE_PATHS += -I../mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed-os/drivers
INCLUDE_PATHS += -I../mbed-os/events
INCLUDE_PATHS += -I../mbed-os/events/equeue
INCLUDE_PATHS += -I../mbed-os/features
INCLUDE_PATHS += -I../mbed-os/features/filesystem
INCLUDE_PATHS += -I../mbed-os/features/filesystem/bd
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I../mbed-os/features/filesystem/littlefs
INCLUDE_PATHS += -I../mbed-os/features/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I../mbed-os/features/frameworks
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/utest
INCLUDE_PATHS += -I../mbed-os/features/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/importer
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32L4
INCLUDE_PATHS += -I../mbed-os/features/nanostack
INCLUDE_PATHS += -I../mbed-os/features/netsocket
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/generic_modem_driver
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/utils
INCLUDE_PATHS += -I../mbed-os/features/storage
INCLUDE_PATHS += -I../mbed-os/hal
INCLUDE_PATHS += -I../mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I../mbed-os/platform
INCLUDE_PATHS += -I../mbed-os/rtos
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Source
INCLUDE_PATHS += -I../mbed-os/targets
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/device
INCLUDE_PATHS += -I../wifi-ism43362
INCLUDE_PATHS += -I../wifi-ism43362/ISM43362
INCLUDE_PATHS += -I../wifi-ism43362/ISM43362/ATParser
INCLUDE_PATHS += -I../wifi-ism43362/ISM43362/ATParser/BufferedSpi
INCLUDE_PATHS += -I../wifi-ism43362/ISM43362/ATParser/BufferedSpi/Buffer
INCLUDE_PATHS += -I../wifi-x-nucleo-idw01m1
INCLUDE_PATHS += -I../wifi-x-nucleo-idw01m1/SPWFSA01
INCLUDE_PATHS += -I../wifi-x-nucleo-idw01m1/SPWFSA04

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-g1' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'


C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1525699582.82
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DUSBHOST_OTHER
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DTARGET_M4
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_STM32L475xG
C_FLAGS += -DTARGET_STM32L4
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DTARGET_DISCO_L475VG_IOT01A
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_FAMILY_STM32
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DTARGET_STM32L475VG
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1525699582.82
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DUSBHOST_OTHER
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_STM32L475xG
CXX_FLAGS += -DTARGET_STM32L4
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DTARGET_DISCO_L475VG_IOT01A
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_FAMILY_STM32
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DTARGET_STM32L475VG
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DUSBHOST_OTHER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -I../.
ASM_FLAGS += -I../wifi-ism43362
ASM_FLAGS += -I../wifi-ism43362/ISM43362
ASM_FLAGS += -I../wifi-ism43362/ISM43362/ATParser
ASM_FLAGS += -I../wifi-ism43362/ISM43362/ATParser/BufferedSpi
ASM_FLAGS += -I../wifi-ism43362/ISM43362/ATParser/BufferedSpi/Buffer
ASM_FLAGS += -I../wifi-x-nucleo-idw01m1
ASM_FLAGS += -I../wifi-x-nucleo-idw01m1/SPWFSA01
ASM_FLAGS += -I../wifi-x-nucleo-idw01m1/SPWFSA04
ASM_FLAGS += -I../VL53L0X
ASM_FLAGS += -I../VL53L0X/STMPE1600
ASM_FLAGS += -I../VL53L0X/X_NUCLEO_COMMON
ASM_FLAGS += -I../VL53L0X/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../VL53L0X/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../VL53L0X/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../VL53L0X/ST_INTERFACES
ASM_FLAGS += -I../VL53L0X/ST_INTERFACES/Actuators
ASM_FLAGS += -I../VL53L0X/ST_INTERFACES/Communications
ASM_FLAGS += -I../VL53L0X/ST_INTERFACES/Common
ASM_FLAGS += -I../VL53L0X/ST_INTERFACES/Sensors
ASM_FLAGS += -I../LSM303AGR
ASM_FLAGS += -I../LSM303AGR/X_NUCLEO_COMMON
ASM_FLAGS += -I../LSM303AGR/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../LSM303AGR/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../LSM303AGR/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../LSM303AGR/ST_INTERFACES
ASM_FLAGS += -I../LSM303AGR/ST_INTERFACES/Actuators
ASM_FLAGS += -I../LSM303AGR/ST_INTERFACES/Communications
ASM_FLAGS += -I../LSM303AGR/ST_INTERFACES/Common
ASM_FLAGS += -I../LSM303AGR/ST_INTERFACES/Sensors
ASM_FLAGS += -I../LSM6DSL
ASM_FLAGS += -I../LSM6DSL/X_NUCLEO_COMMON
ASM_FLAGS += -I../LSM6DSL/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../LSM6DSL/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../LSM6DSL/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../LSM6DSL/ST_INTERFACES
ASM_FLAGS += -I../LSM6DSL/ST_INTERFACES/Actuators
ASM_FLAGS += -I../LSM6DSL/ST_INTERFACES/Communications
ASM_FLAGS += -I../LSM6DSL/ST_INTERFACES/Common
ASM_FLAGS += -I../LSM6DSL/ST_INTERFACES/Sensors
ASM_FLAGS += -I../LPS22HB
ASM_FLAGS += -I../LPS22HB/X_NUCLEO_COMMON
ASM_FLAGS += -I../LPS22HB/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../LPS22HB/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../LPS22HB/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../LPS22HB/ST_INTERFACES
ASM_FLAGS += -I../LPS22HB/ST_INTERFACES/Actuators
ASM_FLAGS += -I../LPS22HB/ST_INTERFACES/Communications
ASM_FLAGS += -I../LPS22HB/ST_INTERFACES/Common
ASM_FLAGS += -I../LPS22HB/ST_INTERFACES/Sensors
ASM_FLAGS += -I../LIS3MDL
ASM_FLAGS += -I../LIS3MDL/X_NUCLEO_COMMON
ASM_FLAGS += -I../LIS3MDL/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../LIS3MDL/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../LIS3MDL/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../LIS3MDL/ST_INTERFACES
ASM_FLAGS += -I../LIS3MDL/ST_INTERFACES/Actuators
ASM_FLAGS += -I../LIS3MDL/ST_INTERFACES/Communications
ASM_FLAGS += -I../LIS3MDL/ST_INTERFACES/Common
ASM_FLAGS += -I../LIS3MDL/ST_INTERFACES/Sensors
ASM_FLAGS += -I../HTS221
ASM_FLAGS += -I../HTS221/X_NUCLEO_COMMON
ASM_FLAGS += -I../HTS221/X_NUCLEO_COMMON/DevSPI
ASM_FLAGS += -I../HTS221/X_NUCLEO_COMMON/DbgMCU
ASM_FLAGS += -I../HTS221/X_NUCLEO_COMMON/DevI2C
ASM_FLAGS += -I../HTS221/ST_INTERFACES
ASM_FLAGS += -I../HTS221/ST_INTERFACES/Actuators
ASM_FLAGS += -I../HTS221/ST_INTERFACES/Communications
ASM_FLAGS += -I../HTS221/ST_INTERFACES/Common
ASM_FLAGS += -I../HTS221/ST_INTERFACES/Sensors
ASM_FLAGS += -I../mbed-os/.
ASM_FLAGS += -I../mbed-os/features
ASM_FLAGS += -I../mbed-os/features/frameworks
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -I../mbed-os/features/frameworks/greentea-client/source
ASM_FLAGS += -I../mbed-os/features/frameworks/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/unity/source
ASM_FLAGS += -I../mbed-os/features/frameworks/unity/unity
ASM_FLAGS += -I../mbed-os/features/frameworks/utest
ASM_FLAGS += -I../mbed-os/features/frameworks/utest/source
ASM_FLAGS += -I../mbed-os/features/frameworks/utest/utest
ASM_FLAGS += -I../mbed-os/features/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/importer
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/inc/mbedtls
ASM_FLAGS += -I../mbed-os/features/mbedtls/src
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform/inc
ASM_FLAGS += -I../mbed-os/features/mbedtls/platform/src
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32L4
ASM_FLAGS += -I../mbed-os/features/nanostack
ASM_FLAGS += -I../mbed-os/features/storage
ASM_FLAGS += -I../mbed-os/features/netsocket
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular/generic_modem_driver
ASM_FLAGS += -I../mbed-os/features/netsocket/cellular/utils
ASM_FLAGS += -I../mbed-os/features/filesystem
ASM_FLAGS += -I../mbed-os/features/filesystem/bd
ASM_FLAGS += -I../mbed-os/features/filesystem/fat
ASM_FLAGS += -I../mbed-os/features/filesystem/fat/ChaN
ASM_FLAGS += -I../mbed-os/features/filesystem/littlefs
ASM_FLAGS += -I../mbed-os/features/filesystem/littlefs/littlefs
ASM_FLAGS += -I../mbed-os/cmsis
ASM_FLAGS += -I../mbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/drivers
ASM_FLAGS += -I../mbed-os/events
ASM_FLAGS += -I../mbed-os/events/equeue
ASM_FLAGS += -I../mbed-os/rtos
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx4
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Include
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
ASM_FLAGS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Source
ASM_FLAGS += -I../mbed-os/hal
ASM_FLAGS += -I../mbed-os/hal/storage_abstraction
ASM_FLAGS += -I../mbed-os/platform
ASM_FLAGS += -I../mbed-os/targets
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/device
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
